In [1]:
import pandas as pd 
import matplotlib.pyplot as plt 
import numpy as np 
import seaborn as sns 
import datetime


from sklearn.preprocessing import OneHotEncoder

In [2]:
mass = pd.read_pickle('./data/02b_added_prosperity.pickle')

In [3]:
mass.head()

,id,country,ccode,year,region,protest,protestnumber,startday,startmonth,startyear,...,stateresponse5,stateresponse6,stateresponse7,sources,notes,PopMale,PopFemale,PopTotal,PopDensity,prosperity_2020
0,201990001,Canada,20,1990,North America,1,1,15.0,1.0,1990.0,...,NaN,NaN,NaN,1. great canadian train journeys into history;...,canada s railway passenger system was finally ...,13656.649,13884.674,27541.323,3.029,79.819703
1,201990002,Canada,20,1990,North America,1,2,25.0,6.0,1990.0,...,NaN,NaN,NaN,1. autonomy s cry revived in quebec the new yo...,protestors were only identified as young peopl...,13656.649,13884.674,27541.323,3.029,79.819703
2,201990003,Canada,20,1990,North America,1,3,1.0,7.0,1990.0,...,NaN,NaN,NaN,1. quebec protest after queen calls for unity ...,"the queen, after calling on canadians to remai...",13656.649,13884.674,27541.323,3.029,79.819703
3,201990004,Canada,20,1990,North America,1,4,12.0,7.0,1990.0,...,NaN,NaN,NaN,1. indians gather as siege intensifies; armed ...,canada s federal government has agreed to acqu...,13656.649,13884.674,27541.323,3.029,79.819703
4,201990005,Canada,20,1990,North America,1,5,14.0,8.0,1990.0,...,NaN,NaN,NaN,1. dozens hurt in mohawk blockade protest the ...,protests were directed against the state due t...,13656.649,13884.674,27541.323,3.029,79.819703

In [66]:
protests = pd.read_csv('./source/mmALL_073120_csv.csv')

### OneHotEncode country, stateresponses & protesterdemands columns

- stateresponses

In [5]:
mass.columns

Index(['id', 'country', 'ccode', 'year', 'region', 'protest', 'protestnumber',
       'startday', 'startmonth', 'startyear', 'endday', 'endmonth', 'endyear',
       'protesterviolence', 'location', 'participants_category',
       'participants', 'protesteridentity', 'protesterdemand1',
       'protesterdemand2', 'protesterdemand3', 'protesterdemand4',
       'stateresponse1', 'stateresponse2', 'stateresponse3', 'stateresponse4',
       'stateresponse5', 'stateresponse6', 'stateresponse7', 'sources',
       'notes', 'PopMale', 'PopFemale', 'PopTotal', 'PopDensity',
       'prosperity_2020'],
      dtype='object')

In [6]:
mass.isnull().sum()

id                           0
country                      0
ccode                        0
year                         0
region                       0
protest                      0
protestnumber                0
startday                     0
startmonth                   0
startyear                    0
endday                       0
endmonth                     0
endyear                      0
protesterviolence            0
location                    21
participants_category     5350
participants                12
protesteridentity          555
protesterdemand1             1
protesterdemand2         12261
protesterdemand3         14854
protesterdemand4         14458
stateresponse1              31
stateresponse2           12350
stateresponse3           14307
stateresponse4           14993
stateresponse5           14440
stateresponse6           15221
stateresponse7           14380
sources                      4
notes                       46
PopMale                      0
PopFemale                    0
PopTotal                     0
PopDensity                   0
prosperity_2020              0
dtype: int64

In [7]:
# fill nulls with 'no response'
mass.fillna('None', inplace=True)

In [8]:
# one hot encode stateresponses
onehot = OneHotEncoder(dtype=np.int, sparse=True)

ohe_df = pd.DataFrame(onehot.fit_transform(mass[['country', 'region','stateresponse1', 'stateresponse2', 'stateresponse3', 'stateresponse4',
       'stateresponse5', 'stateresponse6', 'stateresponse7', 'protesterdemand1',
       'protesterdemand2', 'protesterdemand3', 'protesterdemand4']]).toarray(),
                         columns=onehot.get_feature_names(['country', 'region','stateresponse1', 'stateresponse2', 'stateresponse3', 'stateresponse4',
       'stateresponse5', 'stateresponse6', 'stateresponse7', 'protesterdemand1',
       'protesterdemand2', 'protesterdemand3', 'protesterdemand4']))

In [9]:
ohe_df.columns

Index(['country_Afghanistan', 'country_Albania', 'country_Algeria',
       'country_Angola', 'country_Argentina', 'country_Armenia',
       'country_Austria', 'country_Azerbaijan', 'country_Bahrain',
       'country_Bangladesh',
       ...
       'protesterdemand3_removal of politician',
       'protesterdemand3_social restrictions', 'protesterdemand4_.',
       'protesterdemand4_None', 'protesterdemand4_labor wage dispute',
       'protesterdemand4_land farm issue', 'protesterdemand4_police brutality',
       'protesterdemand4_political behavior, process',
       'protesterdemand4_price increases, tax policy',
       'protesterdemand4_removal of politician'],
      dtype='object', length=256)

In [10]:
ohe_df['arrests'] = ohe_df['stateresponse1_arrests'] + ohe_df['stateresponse2_arrests'] + ohe_df['stateresponse3_arrests'] + ohe_df['stateresponse4_arrests'] + ohe_df['stateresponse5_arrests'] + ohe_df['stateresponse6_arrests'] + ohe_df['stateresponse7_arrests'] 
ohe_df['accomodation'] = ohe_df['stateresponse1_accomodation'] + ohe_df['stateresponse2_accomodation'] + ohe_df['stateresponse3_accomodation'] + ohe_df['stateresponse4_accomodation'] + ohe_df['stateresponse5_accomodation'] + ohe_df['stateresponse6_accomodation'] + ohe_df['stateresponse7_accomodation'] 
ohe_df['beatings'] = ohe_df['stateresponse1_beatings'] + ohe_df['stateresponse2_beatings'] + ohe_df['stateresponse3_beatings'] + ohe_df['stateresponse4_beatings'] + ohe_df['stateresponse5_beatings'] + ohe_df['stateresponse6_beatings'] + ohe_df['stateresponse7_beatings'] 
ohe_df['crowddispersal'] = ohe_df['stateresponse1_crowd dispersal'] + ohe_df['stateresponse2_crowd dispersal'] + ohe_df['stateresponse3_crowd dispersal'] + ohe_df['stateresponse4_crowd dispersal'] + ohe_df['stateresponse5_crowd dispersal'] + ohe_df['stateresponse6_crowd dispersal'] 
ohe_df['ignore'] = ohe_df['stateresponse1_ignore'] + ohe_df['stateresponse2_ignore'] + ohe_df['stateresponse3_ignore']
ohe_df['killings'] = ohe_df['stateresponse1_killings'] + ohe_df['stateresponse2_killings'] + ohe_df['stateresponse3_killings'] + ohe_df['stateresponse4_killings'] + ohe_df['stateresponse5_killings'] + ohe_df['stateresponse6_killings'] + ohe_df['stateresponse7_killings'] 
ohe_df['no_response'] = ohe_df['stateresponse1_None'] + ohe_df['stateresponse2_None'] + ohe_df['stateresponse3_None'] + ohe_df['stateresponse4_None'] + ohe_df['stateresponse5_None'] + ohe_df['stateresponse6_None'] + ohe_df['stateresponse7_None'] 
ohe_df['shootings'] = ohe_df['stateresponse1_shootings'] + ohe_df['stateresponse2_shootings'] + ohe_df['stateresponse3_shootings'] + ohe_df['stateresponse4_shootings'] + ohe_df['stateresponse5_shootings'] 
ohe_df['labor_wage_dispute'] = ohe_df['protesterdemand1_labor wage dispute'] + ohe_df['protesterdemand2_labor wage dispute'] + ohe_df['protesterdemand3_labor wage dispute'] + ohe_df['protesterdemand4_labor wage dispute'] 
ohe_df['land_farm_issue'] = ohe_df['protesterdemand1_land farm issue'] + ohe_df['protesterdemand2_land farm issue'] + ohe_df['protesterdemand3_land farm issue'] + ohe_df['protesterdemand4_land farm issue'] 
ohe_df['no_demands'] = ohe_df['protesterdemand1_None'] + ohe_df['protesterdemand2_None'] + ohe_df['protesterdemand3_None'] + ohe_df['protesterdemand4_None'] 
ohe_df['police_brutality'] = ohe_df['protesterdemand1_police brutality'] + ohe_df['protesterdemand2_police brutality'] + ohe_df['protesterdemand3_police brutality'] + ohe_df['protesterdemand4_police brutality'] 
ohe_df['political_behavior_process'] = ohe_df['protesterdemand1_political behavior, process'] + ohe_df['protesterdemand2_political behavior, process'] + ohe_df['protesterdemand3_political behavior, process'] + ohe_df['protesterdemand4_political behavior, process'] 
ohe_df['price increases_tax_policy'] = ohe_df['protesterdemand1_price increases, tax policy'] + ohe_df['protesterdemand2_price increases, tax policy'] + ohe_df['protesterdemand3_price increases, tax policy'] + ohe_df['protesterdemand4_price increases, tax policy']
ohe_df['removal_of_politician'] = ohe_df['protesterdemand1_removal of politician'] + ohe_df['protesterdemand2_removal of politician'] + ohe_df['protesterdemand3_removal of politician'] + ohe_df['protesterdemand4_removal of politician']
ohe_df['social_restrictions'] = ohe_df['protesterdemand1_social restrictions'] + ohe_df['protesterdemand2_social restrictions'] + ohe_df['protesterdemand3_social restrictions']
ohe_df.head()

,country_Afghanistan,country_Albania,country_Algeria,country_Angola,country_Argentina,country_Armenia,country_Austria,country_Azerbaijan,country_Bahrain,country_Bangladesh,...,no_response,shootings,labor_wage_dispute,land_farm_issue,no_demands,police_brutality,political_behavior_process,price increases_tax_policy,removal_of_politician,social_restrictions
0,0,0,0,0,0,0,0,0,0,0,...,6,0,1,0,2,0,1,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,6,0,0,0,3,0,1,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,6,0,0,0,3,0,1,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,6,0,0,1,3,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,4,0,0,0,3,0,1,0,0,0

In [12]:
ohe_df['no_response'] = ohe_df['no_response'].map(lambda b: 1 if b > 0 else 0)
ohe_df['no_demands'] = ohe_df['no_demands'].map(lambda b: 1 if b > 0 else 0)

ohe_df['no_demands'].unique()

array([1, 0], dtype=int64)

In [13]:
ohe_df.columns

Index(['country_Afghanistan', 'country_Albania', 'country_Algeria',
       'country_Angola', 'country_Argentina', 'country_Armenia',
       'country_Austria', 'country_Azerbaijan', 'country_Bahrain',
       'country_Bangladesh',
       ...
       'no_response', 'shootings', 'labor_wage_dispute', 'land_farm_issue',
       'no_demands', 'police_brutality', 'political_behavior_process',
       'price increases_tax_policy', 'removal_of_politician',
       'social_restrictions'],
      dtype='object', length=272)

In [14]:
mass['protest'].unique()

array([1], dtype=int64)

In [16]:
mass['startday'].head()

0    15.0
1    25.0
2     1.0
3    12.0
4    14.0
Name: startday, dtype: float64

In [17]:
mass['startmonth'].head()

0    1.0
1    6.0
2    7.0
3    7.0
4    8.0
Name: startmonth, dtype: float64

In [ ]:
mass[['day', 'month', 'year']] = mass[['startday', 'startmonth', 'startyear']].astype(int)
mass_protests['start_date'] = pd.to_datetime(mass_protests[['year', 'month', 'day']])
mass[['day', 'month', 'year']].head()

In [67]:
protests.columns

Index(['id', 'country', 'ccode', 'year', 'region', 'protest', 'protestnumber',
       'startday', 'startmonth', 'startyear', 'endday', 'endmonth', 'endyear',
       'protesterviolence', 'location', 'participants_category',
       'participants', 'protesteridentity', 'protesterdemand1',
       'protesterdemand2', 'protesterdemand3', 'protesterdemand4',
       'stateresponse1', 'stateresponse2', 'stateresponse3', 'stateresponse4',
       'stateresponse5', 'stateresponse6', 'stateresponse7', 'sources',
       'notes'],
      dtype='object')

In [68]:
protests.shape

(17145, 31)

In [69]:
protests.head()

,id,country,ccode,year,region,protest,protestnumber,startday,startmonth,startyear,...,protesterdemand4,stateresponse1,stateresponse2,stateresponse3,stateresponse4,stateresponse5,stateresponse6,stateresponse7,sources,notes
0,201990001,Canada,20,1990,North America,1,1,15.0,1.0,1990.0,...,NaN,ignore,NaN,NaN,NaN,NaN,NaN,NaN,1. great canadian train journeys into history;...,canada s railway passenger system was finally ...
1,201990002,Canada,20,1990,North America,1,2,25.0,6.0,1990.0,...,NaN,ignore,NaN,NaN,NaN,NaN,NaN,NaN,1. autonomy s cry revived in quebec the new yo...,protestors were only identified as young peopl...
2,201990003,Canada,20,1990,North America,1,3,1.0,7.0,1990.0,...,NaN,ignore,NaN,NaN,NaN,NaN,NaN,NaN,1. quebec protest after queen calls for unity ...,"the queen, after calling on canadians to remai..."
3,201990004,Canada,20,1990,North America,1,4,12.0,7.0,1990.0,...,NaN,accomodation,NaN,NaN,NaN,NaN,NaN,NaN,1. indians gather as siege intensifies; armed ...,canada s federal government has agreed to acqu...
4,201990005,Canada,20,1990,North America,1,5,14.0,8.0,1990.0,...,NaN,crowd dispersal,arrests,accomodation,NaN,NaN,NaN,NaN,1. dozens hurt in mohawk blockade protest the ...,protests were directed against the state due t...

In [23]:
responses = protests[['id','stateresponse1', 'stateresponse2', 'stateresponse3', 'stateresponse4',
       'stateresponse5', 'stateresponse6', 'stateresponse7']]

In [24]:
responses.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17145 entries, 0 to 17144
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              17145 non-null  int64
 1   stateresponse1  15208 non-null  object
 2   stateresponse2  2888 non-null   object
 3   stateresponse3  930 non-null    object
 4   stateresponse4  244 non-null    object
 5   stateresponse5  849 non-null    object
 6   stateresponse6  16 non-null     object
 7   stateresponse7  920 non-null    object
dtypes: int64(1), object(7)
memory usage: 1.0+ MB

In [26]:
responses.isnull().sum()

id                    0
stateresponse1     1937
stateresponse2    14257
stateresponse3    16215
stateresponse4    16901
stateresponse5    16296
stateresponse6    17129
stateresponse7    16225
dtype: int64

In [70]:
# fill nulls with 'no response'
protests.fillna('None', inplace=True)
#protests.fillna('no demands', inplace=True)

In [9]:
# fill nulls with 'no response'
responses.fillna('no response', inplace=True)
demands.fillna('no demands', inplace=True)

C:\Users\tsuts\anaconda3\lib\site-packages\pandas\core\frame.py:4317: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().fillna(

In [10]:
responses

,id,stateresponse1,stateresponse2,stateresponse3,stateresponse4,stateresponse5,stateresponse6,stateresponse7
0,201990001,ignore,no response,no response,no response,no response,no response,no response
1,201990002,ignore,no response,no response,no response,no response,no response,no response
2,201990003,ignore,no response,no response,no response,no response,no response,no response
3,201990004,accomodation,no response,no response,no response,no response,no response,no response
4,201990005,crowd dispersal,arrests,accomodation,no response,no response,no response,no response
...,...,...,...,...,...,...,...,...
17140,9102017002,crowd dispersal,no response,no response,no response,no response,no response,no response
17141,9102017003,ignore,no response,no response,no response,no response,no response,no response
17142,9102018000,no response,no response,no response,no response,no response,no response,no response
17143,9102019000,no response,no response,no response,no response,.,no response,no response
17144,9102020000,no response,no response,no response,no response,no response,no response,no response

In [71]:
# one hot encode stateresponses
onehot = OneHotEncoder(dtype=np.int, sparse=True)

ohe_df = pd.DataFrame(onehot.fit_transform(protests[['country', 'region','stateresponse1', 'stateresponse2', 'stateresponse3', 'stateresponse4',
       'stateresponse5', 'stateresponse6', 'stateresponse7', 'protesterdemand1',
       'protesterdemand2', 'protesterdemand3', 'protesterdemand4']]).toarray(),
                         columns=onehot.get_feature_names(['country', 'region','stateresponse1', 'stateresponse2', 'stateresponse3', 'stateresponse4',
       'stateresponse5', 'stateresponse6', 'stateresponse7', 'protesterdemand1',
       'protesterdemand2', 'protesterdemand3', 'protesterdemand4']))

In [72]:
onehot.get_feature_names()

array(['x0_Afghanistan', 'x0_Albania', 'x0_Algeria', 'x0_Angola',
       'x0_Argentina', 'x0_Armenia', 'x0_Austria', 'x0_Azerbaijan',
       'x0_Bahrain', 'x0_Bangladesh', 'x0_Belarus', 'x0_Belgium',
       'x0_Benin', 'x0_Bhutan', 'x0_Bolivia', 'x0_Bosnia', 'x0_Botswana',
       'x0_Brazil', 'x0_Bulgaria', 'x0_Burkina Faso', 'x0_Burundi',
       'x0_Cambodia', 'x0_Cameroon', 'x0_Canada', 'x0_Cape Verde',
       'x0_Central African Republic', 'x0_Chad', 'x0_Chile', 'x0_China',
       'x0_Colombia', 'x0_Comoros', 'x0_Congo Brazzaville',
       'x0_Congo Kinshasa', 'x0_Costa Rica', 'x0_Croatia', 'x0_Cuba',
       'x0_Cyprus', 'x0_Czech Republic', 'x0_Czechoslovakia',
       'x0_Denmark', 'x0_Djibouti', 'x0_Dominican Republic', 'x0_Ecuador',
       'x0_Egypt', 'x0_El Salvador', 'x0_Equatorial Guinea', 'x0_Eritrea',
       'x0_Estonia', 'x0_Ethiopia', 'x0_Finland', 'x0_France', 'x0_Gabon',
       'x0_Gambia', 'x0_Georgia', 'x0_Germany', 'x0_Germany East',
       'x0_Germany West', 'x0_Ghana', 'x0_Greece', 'x0_Guatemala',
       'x0_Guinea', 'x0_Guinea-Bissau', 'x0_Guyana', 'x0_Haiti',
       'x0_Honduras', 'x0_Hungary', 'x0_India', 'x0_Indonesia', 'x0_Iran',
       'x0_Iraq', 'x0_Ireland', 'x0_Italy', 'x0_Ivory Coast',
       'x0_Jamaica', 'x0_Japan', 'x0_Jordan', 'x0_Kazakhstan', 'x0_Kenya',
       'x0_Kosovo', 'x0_Kuwait', 'x0_Kyrgyzstan', 'x0_Laos', 'x0_Latvia',
       'x0_Lebanon', 'x0_Lesotho', 'x0_Liberia', 'x0_Libya',
       'x0_Lithuania', 'x0_Luxembourg', 'x0_Macedonia', 'x0_Madagascar',
       'x0_Malawi', 'x0_Malaysia', 'x0_Mali', 'x0_Mauritania',
       'x0_Mauritius', 'x0_Mexico', 'x0_Moldova', 'x0_Mongolia',
       'x0_Montenegro', 'x0_Morocco', 'x0_Mozambique', 'x0_Myanmar',
       'x0_Namibia', 'x0_Nepal', 'x0_Netherlands', 'x0_Nicaragua',
       'x0_Niger', 'x0_Nigeria', 'x0_North Korea', 'x0_Norway', 'x0_Oman',
       'x0_Pakistan', 'x0_Panama', 'x0_Papua New Guinea', 'x0_Paraguay',
       'x0_Peru', 'x0_Philippines', 'x0_Poland', 'x0_Portugal',
       'x0_Qatar', 'x0_Romania', 'x0_Russia', 'x0_Rwanda',
       'x0_Saudi Arabia', 'x0_Senegal', 'x0_Serbia',
       'x0_Serbia and Montenegro', 'x0_Sierra Leone', 'x0_Singapore',
       'x0_Slovak Republic', 'x0_Slovenia', 'x0_Somalia',
       'x0_South Africa', 'x0_South Korea', 'x0_South Sudan', 'x0_Spain',
       'x0_Sri Lanka', 'x0_Sudan', 'x0_Suriname', 'x0_Swaziland',
       'x0_Sweden', 'x0_Switzerland', 'x0_Syria', 'x0_Taiwan',
       'x0_Tajikistan', 'x0_Tanzania', 'x0_Thailand', 'x0_Timor Leste',
       'x0_Togo', 'x0_Tunisia', 'x0_Turkey', 'x0_Turkmenistan', 'x0_USSR',
       'x0_Uganda', 'x0_Ukraine', 'x0_United Arab Emirate',
       'x0_United Kingdom', 'x0_Uruguay', 'x0_Uzbekistan', 'x0_Venezuela',
       'x0_Vietnam', 'x0_Yemen', 'x0_Yugoslavia', 'x0_Zambia',
       'x0_Zimbabwe', 'x1_Africa', 'x1_Asia', 'x1_Central America',
       'x1_Europe', 'x1_MENA', 'x1_North America', 'x1_Oceania',
       'x1_South America', 'x2_None', 'x2_accomodation', 'x2_arrests',
       'x2_beatings', 'x2_crowd dispersal', 'x2_ignore', 'x2_killings',
       'x2_shootings', 'x3_None', 'x3_accomodation', 'x3_arrests',
       'x3_beatings', 'x3_crowd dispersal', 'x3_ignore', 'x3_killings',
       'x3_shootings', 'x4_None', 'x4_accomodation', 'x4_arrests',
       'x4_beatings', 'x4_crowd dispersal', 'x4_ignore', 'x4_killings',
       'x4_shootings', 'x5_None', 'x5_accomodation', 'x5_arrests',
       'x5_beatings', 'x5_crowd dispersal', 'x5_killings', 'x5_shootings',
       'x6_.', 'x6_None', 'x6_accomodation', 'x6_arrests', 'x6_beatings',
       'x6_crowd dispersal', 'x6_killings', 'x6_shootings', 'x7_None',
       'x7_accomodation', 'x7_arrests', 'x7_beatings',
       'x7_crowd dispersal', 'x7_killings', 'x8_.', 'x8_None',
       'x8_accomodation', 'x8_arrests', 'x8_beatings', 'x8_killings',
       'x9_None', 'x9_labor wage dispute', 'x9_land farm issue',
       'x9_police brutality', 'x9_political behavior, process',
       'x9_price increases, tax policy', 'x9_removal of politician',
       'x9_social restrictions', 'x10_None', 'x10_labor wage dispute',
       'x10_land farm issue', 'x10_police brutality',
       'x10_political behavior, process',
       'x10_price increases, tax policy', 'x10_removal of politician',
       'x10_social restrictions', 'x11_None', 'x11_labor wage dispute',
       'x11_land farm issue', 'x11_police brutality',
       'x11_political behavior, process',
       'x11_price increases, tax policy', 'x11_removal of politician',
       'x11_social restrictions', 'x12_.', 'x12_None',
       'x12_labor wage dispute', 'x12_land farm issue',
       'x12_police brutality', 'x12_political behavior, process',
       'x12_price increases, tax policy', 'x12_removal of politician'],
      dtype=object)

In [73]:
ohe_df.columns

Index(['country_Afghanistan', 'country_Albania', 'country_Algeria',
       'country_Angola', 'country_Argentina', 'country_Armenia',
       'country_Austria', 'country_Azerbaijan', 'country_Bahrain',
       'country_Bangladesh',
       ...
       'protesterdemand3_removal of politician',
       'protesterdemand3_social restrictions', 'protesterdemand4_.',
       'protesterdemand4_None', 'protesterdemand4_labor wage dispute',
       'protesterdemand4_land farm issue', 'protesterdemand4_police brutality',
       'protesterdemand4_political behavior, process',
       'protesterdemand4_price increases, tax policy',
       'protesterdemand4_removal of politician'],
      dtype='object', length=257)

In [74]:
ohe_df['arrests'] = ohe_df['stateresponse1_arrests'] + ohe_df['stateresponse2_arrests'] + ohe_df['stateresponse3_arrests'] + ohe_df['stateresponse4_arrests'] + ohe_df['stateresponse5_arrests'] + ohe_df['stateresponse6_arrests'] + ohe_df['stateresponse7_arrests'] 
ohe_df['accomodation'] = ohe_df['stateresponse1_accomodation'] + ohe_df['stateresponse2_accomodation'] + ohe_df['stateresponse3_accomodation'] + ohe_df['stateresponse4_accomodation'] + ohe_df['stateresponse5_accomodation'] + ohe_df['stateresponse6_accomodation'] + ohe_df['stateresponse7_accomodation'] 
ohe_df['beatings'] = ohe_df['stateresponse1_beatings'] + ohe_df['stateresponse2_beatings'] + ohe_df['stateresponse3_beatings'] + ohe_df['stateresponse4_beatings'] + ohe_df['stateresponse5_beatings'] + ohe_df['stateresponse6_beatings'] + ohe_df['stateresponse7_beatings'] 
ohe_df['crowddispersal'] = ohe_df['stateresponse1_crowd dispersal'] + ohe_df['stateresponse2_crowd dispersal'] + ohe_df['stateresponse3_crowd dispersal'] + ohe_df['stateresponse4_crowd dispersal'] + ohe_df['stateresponse5_crowd dispersal'] + ohe_df['stateresponse6_crowd dispersal'] 
ohe_df['ignore'] = ohe_df['stateresponse1_ignore'] + ohe_df['stateresponse2_ignore'] + ohe_df['stateresponse3_ignore']
ohe_df['killings'] = ohe_df['stateresponse1_killings'] + ohe_df['stateresponse2_killings'] + ohe_df['stateresponse3_killings'] + ohe_df['stateresponse4_killings'] + ohe_df['stateresponse5_killings'] + ohe_df['stateresponse6_killings'] + ohe_df['stateresponse7_killings'] 
ohe_df['no_response'] = ohe_df['stateresponse1_None'] + ohe_df['stateresponse2_None'] + ohe_df['stateresponse3_None'] + ohe_df['stateresponse4_None'] + ohe_df['stateresponse5_None'] + ohe_df['stateresponse6_None'] + ohe_df['stateresponse7_None'] 
ohe_df['shootings'] = ohe_df['stateresponse1_shootings'] + ohe_df['stateresponse2_shootings'] + ohe_df['stateresponse3_shootings'] + ohe_df['stateresponse4_shootings'] + ohe_df['stateresponse5_shootings'] 
ohe_df['labor_wage_dispute'] = ohe_df['protesterdemand1_labor wage dispute'] + ohe_df['protesterdemand2_labor wage dispute'] + ohe_df['protesterdemand3_labor wage dispute'] + ohe_df['protesterdemand4_labor wage dispute'] 
ohe_df['land_farm_issue'] = ohe_df['protesterdemand1_land farm issue'] + ohe_df['protesterdemand2_land farm issue'] + ohe_df['protesterdemand3_land farm issue'] + ohe_df['protesterdemand4_land farm issue'] 
ohe_df['no_demands'] = ohe_df['protesterdemand1_None'] + ohe_df['protesterdemand2_None'] + ohe_df['protesterdemand3_None'] + ohe_df['protesterdemand4_None'] 
ohe_df['police_brutality'] = ohe_df['protesterdemand1_police brutality'] + ohe_df['protesterdemand2_police brutality'] + ohe_df['protesterdemand3_police brutality'] + ohe_df['protesterdemand4_police brutality'] 
ohe_df['political_behavior_process'] = ohe_df['protesterdemand1_political behavior, process'] + ohe_df['protesterdemand2_political behavior, process'] + ohe_df['protesterdemand3_political behavior, process'] + ohe_df['protesterdemand4_political behavior, process'] 
ohe_df['price increases_tax_policy'] = ohe_df['protesterdemand1_price increases, tax policy'] + ohe_df['protesterdemand2_price increases, tax policy'] + ohe_df['protesterdemand3_price increases, tax policy'] + ohe_df['protesterdemand4_price increases, tax policy']
ohe_df['removal_of_politician'] = ohe_df['protesterdemand1_removal of politician'] + ohe_df['protesterdemand2_removal of politician'] + ohe_df['protesterdemand3_removal of politician'] + ohe_df['protesterdemand4_removal of politician']
ohe_df['social_restrictions'] = ohe_df['protesterdemand1_social restrictions'] + ohe_df['protesterdemand2_social restrictions'] + ohe_df['protesterdemand3_social restrictions']
ohe_df

,country_Afghanistan,country_Albania,country_Algeria,country_Angola,country_Argentina,country_Armenia,country_Austria,country_Azerbaijan,country_Bahrain,country_Bangladesh,...,no_response,shootings,labor_wage_dispute,land_farm_issue,no_demands,police_brutality,political_behavior_process,price increases_tax_policy,removal_of_politician,social_restrictions
0,0,0,0,0,0,0,0,0,0,0,...,6,0,1,0,2,0,1,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,6,0,0,0,3,0,1,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,6,0,0,0,3,0,1,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,6,0,0,1,3,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,4,0,0,0,3,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17140,0,0,0,0,0,0,0,0,0,0,...,6,0,0,0,3,0,1,0,0,0
17141,0,0,0,0,0,0,0,0,0,0,...,6,0,0,0,3,0,1,0,0,0
17142,0,0,0,0,0,0,0,0,0,0,...,7,0,0,0,4,0,0,0,0,0
17143,0,0,0,0,0,0,0,0,0,0,...,6,0,0,0,3,0,0,0,0,0
17144,0,0,0,0,0,0,0,0,0,0,...,7,0,0,0,4,0,0,0,0,0

In [75]:
ohe_df['no_response'] = ohe_df['no_response'].map(lambda b: 1 if b > 0 else 0)
ohe_df['no_demands'] = ohe_df['no_demands'].map(lambda b: 1 if b > 0 else 0)

ohe_df

,country_Afghanistan,country_Albania,country_Algeria,country_Angola,country_Argentina,country_Armenia,country_Austria,country_Azerbaijan,country_Bahrain,country_Bangladesh,...,no_response,shootings,labor_wage_dispute,land_farm_issue,no_demands,police_brutality,political_behavior_process,price increases_tax_policy,removal_of_politician,social_restrictions
0,0,0,0,0,0,0,0,0,0,0,...,1,0,1,0,1,0,1,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,1,0,1,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,1,0,1,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,1,0,0,1,1,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,1,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17140,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,1,0,1,0,0,0
17141,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,1,0,1,0,0,0
17142,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,0,0
17143,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,0,0
17144,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,0,0

In [65]:
ohe_df = ohe_df[['arrests', 'accomodation', 'beatings',
       'crowddispersal', 'ignore', 'killings', 'no_response', 'shootings', 'labor_wage_dispute',
       'land_farm_issue', 'no_demands', 'police_brutality', 'political_behavior_process',
       'price increases_tax_policy', 'removal_of_politician',
       'social_restrictions']]
ohe_df

,arrests,accomodation,beatings,crowddispersal,ignore,killings,no_response,shootings,labor_wage_dispute,land_farm_issue,no_demands,police_brutality,political_behavior_process,price increases_tax_policy,removal_of_politician,social_restrictions
0,0,0,0,0,1,0,1,0,1,0,1,0,1,0,0,0
1,0,0,0,0,1,0,1,0,0,0,1,0,1,0,0,0
2,0,0,0,0,1,0,1,0,0,0,1,0,1,0,0,0
3,0,1,0,0,0,0,1,0,0,1,1,0,0,0,0,0
4,1,1,0,1,0,0,1,0,0,0,1,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17140,0,0,0,1,0,0,1,0,0,0,1,0,1,0,0,0
17141,0,0,0,0,1,0,1,0,0,0,1,0,1,0,0,0
17142,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0
17143,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0
17144,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0

In [14]:
responses

,stateresponse1_accomodation,stateresponse1_arrests,stateresponse1_beatings,stateresponse1_crowd dispersal,stateresponse1_ignore,stateresponse1_killings,stateresponse1_no response,stateresponse1_shootings,stateresponse2_accomodation,stateresponse2_arrests,...,stateresponse6_beatings,stateresponse6_crowd dispersal,stateresponse6_killings,stateresponse6_no response,stateresponse7_.,stateresponse7_accomodation,stateresponse7_arrests,stateresponse7_beatings,stateresponse7_killings,stateresponse7_no response
0,0,0,0,0,1,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
1,0,0,0,0,1,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
2,0,0,0,0,1,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
3,1,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
4,0,0,0,1,0,0,0,0,0,1,...,0,0,0,1,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17140,0,0,0,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
17141,0,0,0,0,1,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
17142,0,0,0,0,0,0,1,0,0,0,...,0,0,0,1,0,0,0,0,0,1
17143,0,0,0,0,0,0,1,0,0,0,...,0,0,0,1,0,0,0,0,0,1
17144,0,0,0,0,0,0,1,0,0,0,...,0,0,0,1,0,0,0,0,0,1

In [15]:
responses.columns

Index(['stateresponse1_accomodation', 'stateresponse1_arrests',
       'stateresponse1_beatings', 'stateresponse1_crowd dispersal',
       'stateresponse1_ignore', 'stateresponse1_killings',
       'stateresponse1_no response', 'stateresponse1_shootings',
       'stateresponse2_accomodation', 'stateresponse2_arrests',
       'stateresponse2_beatings', 'stateresponse2_crowd dispersal',
       'stateresponse2_ignore', 'stateresponse2_killings',
       'stateresponse2_no response', 'stateresponse2_shootings',
       'stateresponse3_accomodation', 'stateresponse3_arrests',
       'stateresponse3_beatings', 'stateresponse3_crowd dispersal',
       'stateresponse3_ignore', 'stateresponse3_killings',
       'stateresponse3_no response', 'stateresponse3_shootings',
       'stateresponse4_accomodation', 'stateresponse4_arrests',
       'stateresponse4_beatings', 'stateresponse4_crowd dispersal',
       'stateresponse4_killings', 'stateresponse4_no response',
       'stateresponse4_shootings', 'stateresponse5_.',
       'stateresponse5_accomodation', 'stateresponse5_arrests',
       'stateresponse5_beatings', 'stateresponse5_crowd dispersal',
       'stateresponse5_killings', 'stateresponse5_no response',
       'stateresponse5_shootings', 'stateresponse6_accomodation',
       'stateresponse6_arrests', 'stateresponse6_beatings',
       'stateresponse6_crowd dispersal', 'stateresponse6_killings',
       'stateresponse6_no response', 'stateresponse7_.',
       'stateresponse7_accomodation', 'stateresponse7_arrests',
       'stateresponse7_beatings', 'stateresponse7_killings',
       'stateresponse7_no response'],
      dtype='object')

In [16]:
responses['arrests'] = responses['stateresponse1_arrests'] + responses['stateresponse2_arrests'] + responses['stateresponse3_arrests'] + responses['stateresponse4_arrests'] + responses['stateresponse5_arrests'] + responses['stateresponse6_arrests'] + responses['stateresponse7_arrests'] 
responses['accomodation'] = responses['stateresponse1_accomodation'] + responses['stateresponse2_accomodation'] + responses['stateresponse3_accomodation'] + responses['stateresponse4_accomodation'] + responses['stateresponse5_accomodation'] + responses['stateresponse6_accomodation'] + responses['stateresponse7_accomodation'] 
responses['beatings'] = responses['stateresponse1_beatings'] + responses['stateresponse2_beatings'] + responses['stateresponse3_beatings'] + responses['stateresponse4_beatings'] + responses['stateresponse5_beatings'] + responses['stateresponse6_beatings'] + responses['stateresponse7_beatings'] 
responses['crowddispersal'] = responses['stateresponse1_crowd dispersal'] + responses['stateresponse2_crowd dispersal'] + responses['stateresponse3_crowd dispersal'] + responses['stateresponse4_crowd dispersal'] + responses['stateresponse5_crowd dispersal'] + responses['stateresponse6_crowd dispersal'] 
responses['ignore'] = responses['stateresponse1_ignore'] + responses['stateresponse2_ignore'] + responses['stateresponse3_ignore']
responses['killings'] = responses['stateresponse1_killings'] + responses['stateresponse2_killings'] + responses['stateresponse3_killings'] + responses['stateresponse4_killings'] + responses['stateresponse5_killings'] + responses['stateresponse6_killings'] + responses['stateresponse7_killings'] 
responses['no_response'] = responses['stateresponse1_no response'] + responses['stateresponse2_no response'] + responses['stateresponse3_no response'] + responses['stateresponse4_no response'] + responses['stateresponse5_no response'] + responses['stateresponse6_no response'] + responses['stateresponse7_no response'] 
responses['shootings'] = responses['stateresponse1_shootings'] + responses['stateresponse2_shootings'] + responses['stateresponse3_shootings'] + responses['stateresponse4_shootings'] + responses['stateresponse5_shootings'] 
responses

,stateresponse1_accomodation,stateresponse1_arrests,stateresponse1_beatings,stateresponse1_crowd dispersal,stateresponse1_ignore,stateresponse1_killings,stateresponse1_no response,stateresponse1_shootings,stateresponse2_accomodation,stateresponse2_arrests,...,stateresponse7_killings,stateresponse7_no response,arrests,accomodation,beatings,crowddispersal,ignore,killings,no_response,shootings
0,0,0,0,0,1,0,0,0,0,0,...,0,1,0,0,0,0,1,0,6,0
1,0,0,0,0,1,0,0,0,0,0,...,0,1,0,0,0,0,1,0,6,0
2,0,0,0,0,1,0,0,0,0,0,...,0,1,0,0,0,0,1,0,6,0
3,1,0,0,0,0,0,0,0,0,0,...,0,1,0,1,0,0,0,0,6,0
4,0,0,0,1,0,0,0,0,0,1,...,0,1,1,1,0,1,0,0,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17140,0,0,0,1,0,0,0,0,0,0,...,0,1,0,0,0,1,0,0,6,0
17141,0,0,0,0,1,0,0,0,0,0,...,0,1,0,0,0,0,1,0,6,0
17142,0,0,0,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,7,0
17143,0,0,0,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,6,0
17144,0,0,0,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,7,0

In [16]:
state_responses = responses[['arrests', 'accomodation', 'beatings',
       'crowddispersal', 'ignore', 'killings', 'no_response', 'shootings']]
state_responses

,arrests,accomodation,beatings,crowddispersal,ignore,killings,no_response,shootings
0,0,0,0,0,1,0,6,0
1,0,0,0,0,1,0,6,0
2,0,0,0,0,1,0,6,0
3,0,1,0,0,0,0,6,0
4,1,1,0,1,0,0,4,0
...,...,...,...,...,...,...,...,...
17140,0,0,0,1,0,0,6,0
17141,0,0,0,0,1,0,6,0
17142,0,0,0,0,0,0,7,0
17143,0,0,0,0,0,0,6,0
17144,0,0,0,0,0,0,7,0

In [17]:
state_responses['no_response'] = state_responses['no_response'].map(lambda b: 1 if b > 0 else 0)
state_responses

<ipython-input-17-f554de6654c4>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  state_responses['no_response'] = state_responses['no_response'].map(lambda b: 1 if b > 0 else 0)

,arrests,accomodation,beatings,crowddispersal,ignore,killings,no_response,shootings
0,0,0,0,0,1,0,1,0
1,0,0,0,0,1,0,1,0
2,0,0,0,0,1,0,1,0
3,0,1,0,0,0,0,1,0
4,1,1,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...
17140,0,0,0,1,0,0,1,0
17141,0,0,0,0,1,0,1,0
17142,0,0,0,0,0,0,1,0
17143,0,0,0,0,0,0,1,0
17144,0,0,0,0,0,0,1,0

In [18]:
state_responses['no_response'].unique()

array([1, 0], dtype=int64)

In [19]:
# one hot encode protester demands 

demands = protests[['protesterdemand1',
       'protesterdemand2', 'protesterdemand3', 'protesterdemand4']]
demands.head()

,protesterdemand1,protesterdemand2,protesterdemand3,protesterdemand4
0,"political behavior, process",labor wage dispute,NaN,NaN
1,"political behavior, process",NaN,NaN,NaN
2,"political behavior, process",NaN,NaN,NaN
3,land farm issue,NaN,NaN,NaN
4,"political behavior, process",NaN,NaN,NaN

In [20]:
demands.fillna('no demands', inplace=True)

C:\Users\tsuts\anaconda3\lib\site-packages\pandas\core\frame.py:4317: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().fillna(

In [21]:
demands.head()

,protesterdemand1,protesterdemand2,protesterdemand3,protesterdemand4
0,"political behavior, process",labor wage dispute,no demands,no demands
1,"political behavior, process",no demands,no demands,no demands
2,"political behavior, process",no demands,no demands,no demands
3,land farm issue,no demands,no demands,no demands
4,"political behavior, process",no demands,no demands,no demands

In [22]:
onehot = OneHotEncoder(dtype=np.int, sparse=True)
demands = pd.DataFrame(onehot.fit_transform(demands[['protesterdemand1',
       'protesterdemand2', 'protesterdemand3', 'protesterdemand4']]).toarray(),
                         columns=onehot.get_feature_names(['protesterdemand1',
       'protesterdemand2', 'protesterdemand3', 'protesterdemand4']))
onehot.get_feature_names()

array(['x0_labor wage dispute', 'x0_land farm issue', 'x0_no demands',
       'x0_police brutality', 'x0_political behavior, process',
       'x0_price increases, tax policy', 'x0_removal of politician',
       'x0_social restrictions', 'x1_labor wage dispute',
       'x1_land farm issue', 'x1_no demands', 'x1_police brutality',
       'x1_political behavior, process', 'x1_price increases, tax policy',
       'x1_removal of politician', 'x1_social restrictions',
       'x2_labor wage dispute', 'x2_land farm issue', 'x2_no demands',
       'x2_police brutality', 'x2_political behavior, process',
       'x2_price increases, tax policy', 'x2_removal of politician',
       'x2_social restrictions', 'x3_.', 'x3_labor wage dispute',
       'x3_land farm issue', 'x3_no demands', 'x3_police brutality',
       'x3_political behavior, process', 'x3_price increases, tax policy',
       'x3_removal of politician'], dtype=object)

In [23]:
demands.head()

,protesterdemand1_labor wage dispute,protesterdemand1_land farm issue,protesterdemand1_no demands,protesterdemand1_police brutality,"protesterdemand1_political behavior, process","protesterdemand1_price increases, tax policy",protesterdemand1_removal of politician,protesterdemand1_social restrictions,protesterdemand2_labor wage dispute,protesterdemand2_land farm issue,...,protesterdemand3_removal of politician,protesterdemand3_social restrictions,protesterdemand4_.,protesterdemand4_labor wage dispute,protesterdemand4_land farm issue,protesterdemand4_no demands,protesterdemand4_police brutality,"protesterdemand4_political behavior, process","protesterdemand4_price increases, tax policy",protesterdemand4_removal of politician
0,0,0,0,0,1,0,0,0,1,0,...,0,0,0,0,0,1,0,0,0,0
1,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
2,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
3,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
4,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0

In [24]:
demands.columns

Index(['protesterdemand1_labor wage dispute',
       'protesterdemand1_land farm issue', 'protesterdemand1_no demands',
       'protesterdemand1_police brutality',
       'protesterdemand1_political behavior, process',
       'protesterdemand1_price increases, tax policy',
       'protesterdemand1_removal of politician',
       'protesterdemand1_social restrictions',
       'protesterdemand2_labor wage dispute',
       'protesterdemand2_land farm issue', 'protesterdemand2_no demands',
       'protesterdemand2_police brutality',
       'protesterdemand2_political behavior, process',
       'protesterdemand2_price increases, tax policy',
       'protesterdemand2_removal of politician',
       'protesterdemand2_social restrictions',
       'protesterdemand3_labor wage dispute',
       'protesterdemand3_land farm issue', 'protesterdemand3_no demands',
       'protesterdemand3_police brutality',
       'protesterdemand3_political behavior, process',
       'protesterdemand3_price increases, tax policy',
       'protesterdemand3_removal of politician',
       'protesterdemand3_social restrictions', 'protesterdemand4_.',
       'protesterdemand4_labor wage dispute',
       'protesterdemand4_land farm issue', 'protesterdemand4_no demands',
       'protesterdemand4_police brutality',
       'protesterdemand4_political behavior, process',
       'protesterdemand4_price increases, tax policy',
       'protesterdemand4_removal of politician'],
      dtype='object')

In [25]:
demands['labor_wage_dispute'] = demands['protesterdemand1_labor wage dispute'] + demands['protesterdemand2_labor wage dispute'] + demands['protesterdemand3_labor wage dispute'] + demands['protesterdemand4_labor wage dispute'] 
demands['land_farm_issue'] = demands['protesterdemand1_land farm issue'] + demands['protesterdemand2_land farm issue'] + demands['protesterdemand3_land farm issue'] + demands['protesterdemand4_land farm issue'] 
demands['no_demands'] = demands['protesterdemand1_no demands'] + demands['protesterdemand2_no demands'] + demands['protesterdemand3_no demands'] + demands['protesterdemand4_no demands'] 
demands['police_brutality'] = demands['protesterdemand1_police brutality'] + demands['protesterdemand2_police brutality'] + demands['protesterdemand3_police brutality'] + demands['protesterdemand4_police brutality'] 
demands['political_behavior_process'] = demands['protesterdemand1_political behavior, process'] + demands['protesterdemand2_political behavior, process'] + demands['protesterdemand3_political behavior, process'] + demands['protesterdemand4_political behavior, process'] 
demands['price increases_tax_policy'] = demands['protesterdemand1_price increases, tax policy'] + demands['protesterdemand2_price increases, tax policy'] + demands['protesterdemand3_price increases, tax policy'] + demands['protesterdemand4_price increases, tax policy']
demands['removal_of_politician'] = demands['protesterdemand1_removal of politician'] + demands['protesterdemand2_removal of politician'] + demands['protesterdemand3_removal of politician'] + demands['protesterdemand4_removal of politician']
demands['social_restrictions'] = demands['protesterdemand1_social restrictions'] + demands['protesterdemand2_social restrictions'] + demands['protesterdemand3_social restrictions']
demands

,protesterdemand1_labor wage dispute,protesterdemand1_land farm issue,protesterdemand1_no demands,protesterdemand1_police brutality,"protesterdemand1_political behavior, process","protesterdemand1_price increases, tax policy",protesterdemand1_removal of politician,protesterdemand1_social restrictions,protesterdemand2_labor wage dispute,protesterdemand2_land farm issue,...,"protesterdemand4_price increases, tax policy",protesterdemand4_removal of politician,labor_wage_dispute,land_farm_issue,no_demands,police_brutality,political_behavior_process,price increases_tax_policy,removal_of_politician,social_restrictions
0,0,0,0,0,1,0,0,0,1,0,...,0,0,1,0,2,0,1,0,0,0
1,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,3,0,1,0,0,0
2,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,3,0,1,0,0,0
3,0,1,0,0,0,0,0,0,0,0,...,0,0,0,1,3,0,0,0,0,0
4,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,3,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17140,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,3,0,1,0,0,0
17141,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,3,0,1,0,0,0
17142,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,4,0,0,0,0,0
17143,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,3,0,0,0,0,0
17144,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,4,0,0,0,0,0

In [26]:
protest_demands = demands[['labor_wage_dispute',
       'land_farm_issue', 'no_demands', 'police_brutality', 'political_behavior_process',
       'price increases_tax_policy', 'removal_of_politician',
       'social_restrictions']]
protest_demands

,labor_wage_dispute,land_farm_issue,no_demands,police_brutality,political_behavior_process,price increases_tax_policy,removal_of_politician,social_restrictions
0,1,0,2,0,1,0,0,0
1,0,0,3,0,1,0,0,0
2,0,0,3,0,1,0,0,0
3,0,1,3,0,0,0,0,0
4,0,0,3,0,1,0,0,0
...,...,...,...,...,...,...,...,...
17140,0,0,3,0,1,0,0,0
17141,0,0,3,0,1,0,0,0
17142,0,0,4,0,0,0,0,0
17143,0,0,3,0,0,0,0,0
17144,0,0,4,0,0,0,0,0

In [27]:
# concat protest_demands and state_reponses

protest_df = pd.concat([state_responses, protest_demands], axis=1, join='inner')
protest_df

,arrests,accomodation,beatings,crowddispersal,ignore,killings,no_response,shootings,labor_wage_dispute,land_farm_issue,no_demands,police_brutality,political_behavior_process,price increases_tax_policy,removal_of_politician,social_restrictions
0,0,0,0,0,1,0,1,0,1,0,2,0,1,0,0,0
1,0,0,0,0,1,0,1,0,0,0,3,0,1,0,0,0
2,0,0,0,0,1,0,1,0,0,0,3,0,1,0,0,0
3,0,1,0,0,0,0,1,0,0,1,3,0,0,0,0,0
4,1,1,0,1,0,0,1,0,0,0,3,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17140,0,0,0,1,0,0,1,0,0,0,3,0,1,0,0,0
17141,0,0,0,0,1,0,1,0,0,0,3,0,1,0,0,0
17142,0,0,0,0,0,0,1,0,0,0,4,0,0,0,0,0
17143,0,0,0,0,0,0,1,0,0,0,3,0,0,0,0,0
17144,0,0,0,0,0,0,1,0,0,0,4,0,0,0,0,0

In [28]:
# save protests_df (which is one hot encoded df of categorical variables) to csv
protest_df.to_csv('./data/mm_master.csv')

## More Cleaning

In [29]:
protests.head()

,id,country,ccode,year,region,protest,protestnumber,startday,startmonth,startyear,...,protesterdemand4,stateresponse1,stateresponse2,stateresponse3,stateresponse4,stateresponse5,stateresponse6,stateresponse7,sources,notes
0,201990001,Canada,20,1990,North America,1,1,15.0,1.0,1990.0,...,NaN,ignore,NaN,NaN,NaN,NaN,NaN,NaN,1. great canadian train journeys into history;...,canada s railway passenger system was finally ...
1,201990002,Canada,20,1990,North America,1,2,25.0,6.0,1990.0,...,NaN,ignore,NaN,NaN,NaN,NaN,NaN,NaN,1. autonomy s cry revived in quebec the new yo...,protestors were only identified as young peopl...
2,201990003,Canada,20,1990,North America,1,3,1.0,7.0,1990.0,...,NaN,ignore,NaN,NaN,NaN,NaN,NaN,NaN,1. quebec protest after queen calls for unity ...,"the queen, after calling on canadians to remai..."
3,201990004,Canada,20,1990,North America,1,4,12.0,7.0,1990.0,...,NaN,accomodation,NaN,NaN,NaN,NaN,NaN,NaN,1. indians gather as siege intensifies; armed ...,canada s federal government has agreed to acqu...
4,201990005,Canada,20,1990,North America,1,5,14.0,8.0,1990.0,...,NaN,crowd dispersal,arrests,accomodation,NaN,NaN,NaN,NaN,1. dozens hurt in mohawk blockade protest the ...,protests were directed against the state due t...

In [30]:
protests.columns

Index(['id', 'country', 'ccode', 'year', 'region', 'protest', 'protestnumber',
       'startday', 'startmonth', 'startyear', 'endday', 'endmonth', 'endyear',
       'protesterviolence', 'location', 'participants_category',
       'participants', 'protesteridentity', 'protesterdemand1',
       'protesterdemand2', 'protesterdemand3', 'protesterdemand4',
       'stateresponse1', 'stateresponse2', 'stateresponse3', 'stateresponse4',
       'stateresponse5', 'stateresponse6', 'stateresponse7', 'sources',
       'notes'],
      dtype='object')

In [31]:
# create new df with columns of interest
mass_protests = protests[['id', 'country', 'ccode', 'year', 'region', 'protest', 'protestnumber',
       'startday', 'startmonth', 'startyear', 'endday', 'endmonth', 'endyear',
       'protesterviolence', 'location', 'participants_category',
       'participants', 'protesteridentity']]
mass_protests.head()

,id,country,ccode,year,region,protest,protestnumber,startday,startmonth,startyear,endday,endmonth,endyear,protesterviolence,location,participants_category,participants,protesteridentity
0,201990001,Canada,20,1990,North America,1,1,15.0,1.0,1990.0,15.0,1.0,1990.0,0.0,national,NaN,1000s,unspecified
1,201990002,Canada,20,1990,North America,1,2,25.0,6.0,1990.0,25.0,6.0,1990.0,0.0,"Montreal, Quebec",NaN,1000,unspecified
2,201990003,Canada,20,1990,North America,1,3,1.0,7.0,1990.0,1.0,7.0,1990.0,0.0,"Montreal, Quebec",NaN,500,separatist parti quebecois
3,201990004,Canada,20,1990,North America,1,4,12.0,7.0,1990.0,6.0,9.0,1990.0,1.0,"Montreal, Quebec",NaN,100s,mohawk indians
4,201990005,Canada,20,1990,North America,1,5,14.0,8.0,1990.0,15.0,8.0,1990.0,1.0,"Montreal, Quebec",NaN,950,local residents

In [33]:
# add encoded df 
mass_protests = pd.concat([mass_protests, protest_df], axis=1, join="inner")

In [34]:
mass_protests.head()

,id,country,ccode,year,region,protest,protestnumber,startday,startmonth,startyear,...,no_response,shootings,labor_wage_dispute,land_farm_issue,no_demands,police_brutality,political_behavior_process,price increases_tax_policy,removal_of_politician,social_restrictions
0,201990001,Canada,20,1990,North America,1,1,15.0,1.0,1990.0,...,1,0,1,0,2,0,1,0,0,0
1,201990002,Canada,20,1990,North America,1,2,25.0,6.0,1990.0,...,1,0,0,0,3,0,1,0,0,0
2,201990003,Canada,20,1990,North America,1,3,1.0,7.0,1990.0,...,1,0,0,0,3,0,1,0,0,0
3,201990004,Canada,20,1990,North America,1,4,12.0,7.0,1990.0,...,1,0,0,1,3,0,0,0,0,0
4,201990005,Canada,20,1990,North America,1,5,14.0,8.0,1990.0,...,1,0,0,0,3,0,1,0,0,0

In [35]:
mass_protests.shape

(17145, 34)

In [36]:
mass_protests.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17145 entries, 0 to 17144
Data columns (total 34 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   id                          17145 non-null  int64
 1   country                     17145 non-null  object
 2   ccode                       17145 non-null  int64
 3   year                        17145 non-null  int64
 4   region                      17145 non-null  object
 5   protest                     17145 non-null  int64
 6   protestnumber               17145 non-null  int64
 7   startday                    15239 non-null  float64
 8   startmonth                  15239 non-null  float64
 9   startyear                   15239 non-null  float64
 10  endday                      15239 non-null  float64
 11  endmonth                    15239 non-null  float64
 12  endyear                     15239 non-null  float64
 13  protesterviolence           15758 non-null  float64
 14  location                    15218 non-null  object
 15  participants_category       9887 non-null   object
 16  participants                15746 non-null  object
 17  protesteridentity           14684 non-null  object
 18  arrests                     17145 non-null  int32
 19  accomodation                17145 non-null  int32
 20  beatings                    17145 non-null  int32
 21  crowddispersal              17145 non-null  int32
 22  ignore                      17145 non-null  int32
 23  killings                    17145 non-null  int32
 24  no_response                 17145 non-null  int64
 25  shootings                   17145 non-null  int32
 26  labor_wage_dispute          17145 non-null  int32
 27  land_farm_issue             17145 non-null  int32
 28  no_demands                  17145 non-null  int32
 29  police_brutality            17145 non-null  int32
 30  political_behavior_process  17145 non-null  int32
 31  price increases_tax_policy  17145 non-null  int32
 32  removal_of_politician       17145 non-null  int32
 33  social_restrictions         17145 non-null  int32
dtypes: float64(7), int32(15), int64(6), object(6)
memory usage: 3.5+ MB

In [37]:
mass_protests.isnull().sum()

id                               0
country                          0
ccode                            0
year                             0
region                           0
protest                          0
protestnumber                    0
startday                      1906
startmonth                    1906
startyear                     1906
endday                        1906
endmonth                      1906
endyear                       1906
protesterviolence             1387
location                      1927
participants_category         7258
participants                  1399
protesteridentity             2461
arrests                          0
accomodation                     0
beatings                         0
crowddispersal                   0
ignore                           0
killings                         0
no_response                      0
shootings                        0
labor_wage_dispute               0
land_farm_issue                  0
no_demands                       0
police_brutality                 0
political_behavior_process       0
price increases_tax_policy       0
removal_of_politician            0
social_restrictions              0
dtype: int64

- we found that by dropping protest=0, a lot of the null values from out date columns are also dropped
- we decided to just drop our protest=0 rows because we are only interested in protests=1 anyways

In [38]:
mass_protests = mass_protests[mass_protests['protest']==1]
mass_protests.isnull().sum()

id                               0
country                          0
ccode                            0
year                             0
region                           0
protest                          0
protestnumber                    0
startday                         0
startmonth                       0
startyear                        0
endday                           0
endmonth                         0
endyear                          0
protesterviolence                0
location                        21
participants_category         5352
participants                    12
protesteridentity              555
arrests                          0
accomodation                     0
beatings                         0
crowddispersal                   0
ignore                           0
killings                         0
no_response                      0
shootings                        0
labor_wage_dispute               0
land_farm_issue                  0
no_demands                       0
police_brutality                 0
political_behavior_process       0
price increases_tax_policy       0
removal_of_politician            0
social_restrictions              0
dtype: int64

In [39]:
mass_protests['startday'].head()

0    15.0
1    25.0
2     1.0
3    12.0
4    14.0
Name: startday, dtype: float64

In [40]:
mass_protests['startmonth'].head()

0    1.0
1    6.0
2    7.0
3    7.0
4    8.0
Name: startmonth, dtype: float64

In [41]:
mass_protests[['day', 'month', 'year']] = mass_protests[['startday', 'startmonth', 'startyear']].astype(int)
mass_protests[['day', 'month', 'year']].head()

   day  month  year
0   15      1  1990
1   25      6  1990
2    1      7  1990
3   12      7  1990
4   14      8  1990

In [42]:
mass_protests['start_date'] = pd.to_datetime(mass_protests[['year', 'month', 'day']])

In [43]:
mass_protests['start_date']

0       1990-01-15
1       1990-06-25
2       1990-07-01
3       1990-07-12
4       1990-08-14
           ...
17136   2014-02-16
17138   2016-05-15
17139   2017-06-15
17140   2017-07-15
17141   2017-10-31
Name: start_date, Length: 15239, dtype: datetime64[ns]

- now do same thing with enddates

In [44]:
mass_protests[['day', 'month', 'year']] = mass_protests[['endday', 'endmonth', 'endyear']].astype(int)

mass_protests['end_date'] = pd.to_datetime(mass_protests[['year', 'month', 'day']])
mass_protests['end_date']

0       1990-01-15
1       1990-06-25
2       1990-07-01
3       1990-09-06
4       1990-08-15
           ...
17136   2014-02-18
17138   2016-06-09
17139   2017-06-15
17140   2017-07-15
17141   2017-10-31
Name: end_date, Length: 15239, dtype: datetime64[ns]

In [45]:
mass_protests.columns

Index(['id', 'country', 'ccode', 'year', 'region', 'protest', 'protestnumber',
       'startday', 'startmonth', 'startyear', 'endday', 'endmonth', 'endyear',
       'protesterviolence', 'location', 'participants_category',
       'participants', 'protesteridentity', 'arrests', 'accomodation',
       'beatings', 'crowddispersal', 'ignore', 'killings', 'no_response',
       'shootings', 'labor_wage_dispute', 'land_farm_issue', 'no_demands',
       'police_brutality', 'political_behavior_process',
       'price increases_tax_policy', 'removal_of_politician',
       'social_restrictions', 'day', 'month', 'start_date', 'end_date'],
      dtype='object')

In [48]:
mass_protests.drop(columns=['startday', 'startmonth', 'startyear', 'endday', 'endmonth', 'endyear', 'day', 'month'], inplace=True)

In [49]:
mass_protests.head()

,id,country,ccode,year,region,protest,protestnumber,protesterviolence,location,participants_category,...,labor_wage_dispute,land_farm_issue,no_demands,police_brutality,political_behavior_process,price increases_tax_policy,removal_of_politician,social_restrictions,start_date,end_date
0,201990001,Canada,20,1990,North America,1,1,0.0,national,NaN,...,1,0,2,0,1,0,0,0,1990-01-15,1990-01-15
1,201990002,Canada,20,1990,North America,1,2,0.0,"Montreal, Quebec",NaN,...,0,0,3,0,1,0,0,0,1990-06-25,1990-06-25
2,201990003,Canada,20,1990,North America,1,3,0.0,"Montreal, Quebec",NaN,...,0,0,3,0,1,0,0,0,1990-07-01,1990-07-01
3,201990004,Canada,20,1990,North America,1,4,1.0,"Montreal, Quebec",NaN,...,0,1,3,0,0,0,0,0,1990-07-12,1990-09-06
4,201990005,Canada,20,1990,North America,1,5,1.0,"Montreal, Quebec",NaN,...,0,0,3,0,1,0,0,0,1990-08-14,1990-08-15

In [50]:
# save updated df with datetime columns to master csv
mass_protests.to_csv('./data/mm_master.csv')

- some of the gov response columns have values that are greater than 1. This means that in some cases the government's response was used multiple times for the same protest. For example, on day one of a protest, the government arrested some protesters, and on day five of the protest, they arrested more people. This result in a value of 2 in the arrest column. 

- I do think that there is potentially something to gain from somehow incorporating the number of times the goverment had the same response for the same protest, but for now I want to dummify these columns.

In [52]:
mass_protests.columns

Index(['id', 'country', 'ccode', 'year', 'region', 'protest', 'protestnumber',
       'protesterviolence', 'location', 'participants_category',
       'participants', 'protesteridentity', 'arrests', 'accomodation',
       'beatings', 'crowddispersal', 'ignore', 'killings', 'no_response',
       'shootings', 'labor_wage_dispute', 'land_farm_issue', 'no_demands',
       'police_brutality', 'political_behavior_process',
       'price increases_tax_policy', 'removal_of_politician',
       'social_restrictions', 'start_date', 'end_date'],
      dtype='object')

In [53]:
for i in mass_protests[['arrests', 'accomodation',
       'beatings', 'crowddispersal', 'ignore', 'killings', 'no_response',
       'shootings']]: 
    print(i)

arrests
accomodation
beatings
crowddispersal
ignore
killings
no_response
shootings

In [54]:
mass_protests['arrests'] = mass_protests['arrests'].map(lambda x: 1 if x >= 1 else 0)
mass_protests['accomodation'] = mass_protests['accomodation'].map(lambda x: 1 if x >= 1 else 0)
mass_protests['beatings'] = mass_protests['beatings'].map(lambda x: 1 if x >= 1 else 0)
mass_protests['crowddispersal'] = mass_protests['crowddispersal'].map(lambda x: 1 if x >= 1 else 0)
mass_protests['ignore'] = mass_protests['ignore'].map(lambda x: 1 if x >= 1 else 0)
mass_protests['killings'] = mass_protests['killings'].map(lambda x: 1 if x >= 1 else 0)
mass_protests['no_response'] = mass_protests['no_response'].map(lambda x: 1 if x >= 1 else 0)
mass_protests['shootings'] = mass_protests['shootings'].map(lambda x: 1 if x >= 1 else 0)

mass_protests.head()

,id,country,ccode,year,region,protest,protestnumber,protesterviolence,location,participants_category,...,labor_wage_dispute,land_farm_issue,no_demands,police_brutality,political_behavior_process,price increases_tax_policy,removal_of_politician,social_restrictions,start_date,end_date
0,201990001,Canada,20,1990,North America,1,1,0.0,national,NaN,...,1,0,2,0,1,0,0,0,1990-01-15,1990-01-15
1,201990002,Canada,20,1990,North America,1,2,0.0,"Montreal, Quebec",NaN,...,0,0,3,0,1,0,0,0,1990-06-25,1990-06-25
2,201990003,Canada,20,1990,North America,1,3,0.0,"Montreal, Quebec",NaN,...,0,0,3,0,1,0,0,0,1990-07-01,1990-07-01
3,201990004,Canada,20,1990,North America,1,4,1.0,"Montreal, Quebec",NaN,...,0,1,3,0,0,0,0,0,1990-07-12,1990-09-06
4,201990005,Canada,20,1990,North America,1,5,1.0,"Montreal, Quebec",NaN,...,0,0,3,0,1,0,0,0,1990-08-14,1990-08-15

In [61]:
# save updated df to master csv
mass_protests.to_csv('./data/mm_master.csv')

In [62]:
mass_protests.isnull().sum()

id                               0
country                          0
ccode                            0
year                             0
region                           0
protest                          0
protestnumber                    0
protesterviolence                0
location                        21
participants_category         5352
participants                    12
protesteridentity              555
arrests                          0
accomodation                     0
beatings                         0
crowddispersal                   0
ignore                           0
killings                         0
no_response                      0
shootings                        0
labor_wage_dispute               0
land_farm_issue                  0
no_demands                       0
police_brutality                 0
political_behavior_process       0
price increases_tax_policy       0
removal_of_politician            0
social_restrictions              0
start_date                       0
end_date                         0
dtype: int64

In [63]:
mass_protests['location'].unique()

array(['national', 'Montreal, Quebec',
       'Kahnawake Reservation near Montreal, Quebec', ..., 'Bougainville',
       'Mount Hagen', 'Lorengau'], dtype=object)