In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
pwd

'/Users/emilynaftalin/Data_Science/General Assembly/dsi/projects/Mass-Protests/users'

In [3]:
mass = pd.read_csv('../source/mmALL_073120_csv.csv')

In [4]:
mass.head()

,id,country,ccode,year,region,protest,protestnumber,startday,startmonth,startyear,...,protesterdemand4,stateresponse1,stateresponse2,stateresponse3,stateresponse4,stateresponse5,stateresponse6,stateresponse7,sources,notes
0,201990001,Canada,20,1990,North America,1,1,15.0,1.0,1990.0,...,NaN,ignore,NaN,NaN,NaN,NaN,NaN,NaN,1. great canadian train journeys into history;...,canada s railway passenger system was finally ...
1,201990002,Canada,20,1990,North America,1,2,25.0,6.0,1990.0,...,NaN,ignore,NaN,NaN,NaN,NaN,NaN,NaN,1. autonomy s cry revived in quebec the new yo...,protestors were only identified as young peopl...
2,201990003,Canada,20,1990,North America,1,3,1.0,7.0,1990.0,...,NaN,ignore,NaN,NaN,NaN,NaN,NaN,NaN,1. quebec protest after queen calls for unity ...,"the queen, after calling on canadians to remai..."
3,201990004,Canada,20,1990,North America,1,4,12.0,7.0,1990.0,...,NaN,accomodation,NaN,NaN,NaN,NaN,NaN,NaN,1. indians gather as siege intensifies; armed ...,canada s federal government has agreed to acqu...
4,201990005,Canada,20,1990,North America,1,5,14.0,8.0,1990.0,...,NaN,crowd dispersal,arrests,accomodation,NaN,NaN,NaN,NaN,1. dozens hurt in mohawk blockade protest the ...,protests were directed against the state due t...

In [ ]:
prosperity_df = pd.read_excel('../data/Prosperity_Index.xlsx', sheet_name=1)

In [5]:
mass.isnull().sum()

id                           0
country                      0
ccode                        0
year                         0
region                       0
protest                      0
protestnumber                0
startday                  1906
startmonth                1906
startyear                 1906
endday                    1906
endmonth                  1906
endyear                   1906
protesterviolence         1387
location                  1927
participants_category     7258
participants              1399
protesteridentity         2461
protesterdemand1          1907
protesterdemand2         14168
protesterdemand3         16762
protesterdemand4         16314
stateresponse1            1937
stateresponse2           14257
stateresponse3           16215
stateresponse4           16901
stateresponse5           16296
stateresponse6           17129
stateresponse7           16225
sources                   1910
notes                     1952
dtype: int64

In [22]:
mass['protesterdemand1'].value_counts()

political behavior, process    9680
labor wage dispute             1710
price increases, tax policy    1087
removal of politician          1011
police brutality                825
land farm issue                 467
social restrictions             458
Name: protesterdemand1, dtype: int64

In [23]:
mass['protesterdemand2'].value_counts()

political behavior, process    1004
removal of politician           768
labor wage dispute              438
police brutality                241
price increases, tax policy     214
social restrictions             212
land farm issue                 100
Name: protesterdemand2, dtype: int64

In [24]:
mass.groupby(['stateresponse2', 'stateresponse1', 'stateresponse3']).count()

                                                id  country  ccode  year  \
stateresponse2 stateresponse1  stateresponse3
accomodation   arrests         beatings          1        1      1     1
                               crowd dispersal   4        4      4     4
                               ignore            1        1      1     1
                               shootings         1        1      1     1
               crowd dispersal arrests           2        2      2     2
...                                             ..      ...    ...   ...
shootings      ignore          killings          3        3      3     3
               killings        accomodation      2        2      2     2
                               arrests           6        6      6     6
                               beatings          8        8      8     8
                               crowd dispersal  38       38     38    38

                                                region  protest  \
stateresponse2 stateresponse1  stateresponse3
accomodation   arrests         beatings              1        1
                               crowd dispersal       4        4
                               ignore                1        1
                               shootings             1        1
               crowd dispersal arrests               2        2
...                                                ...      ...
shootings      ignore          killings              3        3
               killings        accomodation          2        2
                               arrests               6        6
                               beatings              8        8
                               crowd dispersal      38       38

                                                protestnumber  startday  \
stateresponse2 stateresponse1  stateresponse3
accomodation   arrests         beatings                     1         1
                               crowd dispersal              4         4
                               ignore                       1         1
                               shootings                    1         1
               crowd dispersal arrests                      2         2
...                                                       ...       ...
shootings      ignore          killings                     3         3
               killings        accomodation                 2         2
                               arrests                      6         6
                               beatings                     8         8
                               crowd dispersal             38        38

                                                startmonth  startyear  ...  \
stateresponse2 stateresponse1  stateresponse3                          ...
accomodation   arrests         beatings                  1          1  ...
                               crowd dispersal           4          4  ...
                               ignore                    1          1  ...
                               shootings                 1          1  ...
               crowd dispersal arrests                   2          2  ...
...                                                    ...        ...  ...
shootings      ignore          killings                  3          3  ...
               killings        accomodation              2          2  ...
                               arrests                   6          6  ...
                               beatings                  8          8  ...
                               crowd dispersal          38         38  ...

                                                protesterdemand1  \
stateresponse2 stateresponse1  stateresponse3
accomodation   arrests         beatings                        1
                               crowd dispersal                 4
                               ignore                          1
                               shootings                       1
               crowd dispersal arrests                         2
...                                                          ...
shootings      ignore          killings                        3
               killings        accomodation                    2
                               arrests                         6
                               beatings                        8
                               crowd dispersal                38

                                                protesterdemand2  \
stateresponse2 stateresponse1  stateresponse3
accomodation   arrests         beatings                        1
                               crowd dispersal                 2
                               ignore                          0
                               shootings                       0
               crowd dispersal arrests                         0
...                                                          ...
shootings      ignore          killings                        0
               killings        accomodation                    0
                               arrests                         0
                               beatings                        3
                               crowd dispersal                 5

                                                protesterdemand3  \
stateresponse2 stateresponse1  stateresponse3
accomodation   arrests         beatings                        1
                               crowd dispersal                 2
                               ignore                          0
                               shootings                       0
               crowd dispersal arrests                         0
...                                                          ...
shootings      ignore          killings                        0
               killings        accomodation                    0
                               arrests                         0
                               beatings                        1
                               crowd dispersal                 0

                                                protesterdemand4  \
stateresponse2 stateresponse1  stateresponse3
accomodation   arrests         beatings                        0
                               crowd dispersal                 1
                               ignore                          0
                               shootings                       0
               crowd dispersal arrests                         0
...                                                          ...
shootings      ignore          killings                        0
               killings        accomodation                    1
                               arrests                         2
                               beatings                        2
                               crowd dispersal                10

                                                stateresponse4  \
stateresponse2 stateresponse1  stateresponse3
accomodation   arrests         beatings                      1
                               crowd dispersal               2
                               ignore                        0
                               shootings                     1
               crowd dispersal arrests                       1
...                                                        ...
shootings      ignore          killings                      0
               killings        accomodation                  0
                               arrests                       6
                               beatings                      6
                               crowd dispersal               9

                                                stateresponse5  \
stateresponse2 stateresponse1  stateresponse3
accomodation   arrests         beatings                      0
                               crowd dispersal               0
                               ignore                        0
                               shootings                     0
               crowd dispersal arrests                       0
...                                                        ...
shootings      ignore          killings                      0
               killings        accomodation                  1
                               arrests                       2
                               beatings                      4
                               crowd dispersal              10

                                                stateresponse6  \
stateresponse2 stateresponse1  stateresponse3
accomodation   arrests         beatings                      0
                               crowd dispersal               0
                               ignore                        0
                               shootings                     0
               crowd dispersal arrests                       0
...                                                        ...
shootings      ignore          killings                      0
               killings        accomodation                  0
                               arrests                       0
                               beatings                      1
                               crowd dispersal               0

                                                stateresponse7  sources  notes
stateresponse2 stateresponse1  stateresponse3
accomodation   arrests         beatings                      0        1      1
                               crowd dispersal               0        4      4
                               ignore                        0        1      1
                               shootings                     0        1      1
               crowd dispersal arrests                       0        2      2
...                                                        ...      ...    ...
shootings      ignore          killings                      0        3      3
               killings        accomodation                  0        2      2
                               arrests                       0        6      6
                               beatings                      0        8      8
                               crowd dispersal               0       38     38

[112 rows x 28 columns]

In [25]:
mass[mass['country']=='Senegal'].groupby('location').count()

,id,country,ccode,year,region,protest,protestnumber,startday,startmonth,startyear,...,protesterdemand4,stateresponse1,stateresponse2,stateresponse3,stateresponse4,stateresponse5,stateresponse6,stateresponse7,sources,notes
location,,,,,,,,,,,,,,,,,,,,,
Bandia,1,1,1,1,1,1,1,1,1,1,...,0,1,0,0,0,0,0,0,1,1
Dakar,34,34,34,34,34,34,34,34,34,34,...,1,34,6,2,2,2,0,0,34,34
Dakar and Podor,3,3,3,3,3,3,3,3,3,3,...,0,3,1,1,0,0,0,0,3,3
"Dakar, Thies, and Kaolack",1,1,1,1,1,1,1,1,1,1,...,0,1,0,0,0,0,0,0,1,1
Kedougou,1,1,1,1,1,1,1,1,1,1,...,0,1,0,0,0,0,0,0,1,1
"Nationwide, including Dakar; Ziguinchor; Bambey; Thies",1,1,1,1,1,1,1,1,1,1,...,1,1,0,0,0,1,0,0,1,1
Saint Louis,1,1,1,1,1,1,1,1,1,1,...,0,1,0,0,0,0,0,0,1,1
Velingara,1,1,1,1,1,1,1,1,1,1,...,0,1,0,0,0,0,0,0,1,1
natonal,1,1,1,1,1,1,1,1,1,1,...,0,1,0,0,0,0,0,0,1,1
ziguinchor,1,1,1,1,1,1,1,1,1,1,...,0,1,0,0,0,0,0,0,1,1

In [27]:
mass[mass['protestnumber']>75].groupby('country').count()

,id,ccode,year,region,protest,protestnumber,startday,startmonth,startyear,endday,...,protesterdemand4,stateresponse1,stateresponse2,stateresponse3,stateresponse4,stateresponse5,stateresponse6,stateresponse7,sources,notes
country,,,,,,,,,,,,,,,,,,,,,
Kenya,68,68,68,68,68,68,68,68,68,68,...,2,68,10,4,0,0,0,68,68,68
Ukraine,16,16,16,16,16,16,16,16,16,16,...,0,16,4,1,0,0,0,0,16,16

In [28]:
set(list(mass[mass['protestnumber']>50]['country']))

{'Algeria',
 'Bangladesh',
 'China',
 'Cuba',
 'Germany',
 'Ireland',
 'Kenya',
 'Lebanon',
 'Nigeria',
 'Romania',
 'Ukraine',
 'Yemen'}

In [29]:
mass[mass['protestnumber']>50]['country']

173            Cuba
174            Cuba
175            Cuba
3740        Ireland
3741        Ireland
            ...
15831    Bangladesh
15832    Bangladesh
15833    Bangladesh
15834    Bangladesh
15835    Bangladesh
Name: country, Length: 237, dtype: object

In [30]:
mass['protestnumber'].value_counts()

1      2970
2      2141
0      1906
3      1620
4      1269
       ...
136       1
105       1
121       1
137       1
135       1
Name: protestnumber, Length: 144, dtype: int64

In [31]:
mass.groupby('country').count()

,id,ccode,year,region,protest,protestnumber,startday,startmonth,startyear,endday,...,protesterdemand4,stateresponse1,stateresponse2,stateresponse3,stateresponse4,stateresponse5,stateresponse6,stateresponse7,sources,notes
country,,,,,,,,,,,,,,,,,,,,,
Afghanistan,56,56,56,56,56,56,39,39,39,39,...,6,39,5,0,0,6,0,5,39,39
Albania,93,93,93,93,93,93,78,78,78,78,...,18,78,28,2,0,18,0,1,78,78
Algeria,122,122,122,122,122,122,105,105,105,105,...,20,105,5,0,0,20,0,3,105,105
Angola,38,38,38,38,38,38,24,24,24,24,...,1,24,8,1,0,1,0,3,24,24
Argentina,118,118,118,118,118,118,115,115,115,115,...,6,114,24,5,0,6,0,5,115,115
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Vietnam,36,36,36,36,36,36,19,19,19,19,...,2,19,9,1,0,2,0,1,19,18
Yemen,166,166,166,166,166,166,157,157,157,157,...,2,157,46,17,5,3,1,11,157,157
Yugoslavia,138,138,138,138,138,138,137,137,137,137,...,3,137,33,13,5,0,0,0,137,137
Zambia,99,99,99,99,99,99,95,95,95,95,...,1,95,29,11,2,1,0,1,94,95
Zimbabwe,119,119,119,119,119,119,115,115,115,115,...,9,115,46,16,7,9,0,3,115,115

In [36]:
(mass[mass['protestnumber']>75])['country'].value_counts()

Kenya      68
Ukraine    16
Name: country, dtype: int64

In [37]:
(mass[mass['protestnumber']>75])

pandas.core.frame.DataFrame

In [47]:
mass[['protestnumber','country']][mass['protestnumber']>50].groupby('country').count()

            protestnumber  participants
country
Algeria                16            16
Bangladesh             19            19
China                   6             6
Cuba                    3             3
Germany                12            12
Ireland                 6             6
Kenya                  93            93
Lebanon                12            12
Nigeria                 8             8
Romania                13            13
Ukraine                41            41
Yemen                   8             8

In [50]:
mass[['protestnumber','country', 'location']][mass['protestnumber']>50]

       protestnumber     country    location
173               51        Cuba      Havana
174               52        Cuba      Havana
175               53        Cuba      Havana
3740              51     Ireland      Dublin
3741              52     Ireland    Jobstown
...              ...         ...         ...
15831             55  Bangladesh  Chittagong
15832             56  Bangladesh       Dhaka
15833             57  Bangladesh       Dhaka
15834             58  Bangladesh     Gazipur
15835             59  Bangladesh  nationwide

[237 rows x 3 columns]

In [43]:
mass['participants_category']

0            NaN
1            NaN
2            NaN
3            NaN
4            NaN
          ...
17140      50-99
17141    100-999
17142        NaN
17143        NaN
17144        NaN
Name: participants_category, Length: 17145, dtype: object

In [56]:
mass.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17145 entries, 0 to 17144
Data columns (total 31 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     17145 non-null  int64
 1   country                17145 non-null  object
 2   ccode                  17145 non-null  int64
 3   year                   17145 non-null  int64
 4   region                 17145 non-null  object
 5   protest                17145 non-null  int64
 6   protestnumber          17145 non-null  int64
 7   startday               15239 non-null  float64
 8   startmonth             15239 non-null  float64
 9   startyear              15239 non-null  float64
 10  endday                 15239 non-null  float64
 11  endmonth               15239 non-null  float64
 12  endyear                15239 non-null  float64
 13  protesterviolence      15758 non-null  float64
 14  location               15218 non-null  object
 15  participants_category  9887 non-null   object
 16  participants           15746 non-null  object
 17  protesteridentity      14684 non-null  object
 18  protesterdemand1       15238 non-null  object
 19  protesterdemand2       2977 non-null   object
 20  protesterdemand3       383 non-null    object
 21  protesterdemand4       831 non-null    object
 22  stateresponse1         15208 non-null  object
 23  stateresponse2         2888 non-null   object
 24  stateresponse3         930 non-null    object
 25  stateresponse4         244 non-null    object
 26  stateresponse5         849 non-null    object
 27  stateresponse6         16 non-null     object
 28  stateresponse7         920 non-null    object
 29  sources                15235 non-null  object
 30  notes                  15193 non-null  object
dtypes: float64(7), int64(5), object(19)
memory usage: 4.1+ MB

In [55]:
pwd

'/Users/emilynaftalin/Data_Science/General Assembly/dsi/projects/Mass-Protests/users'

In [ ]:
responses = pd.read_csv('../data/mm_master.csv')